FROM ubuntu:24.04

ARG email
ARG api_key

ENV N_THREADS=1
ENV COHMETRIX_EMAIL=${email}
ENV COHMETRIX_API_KEY=${api_key}

# Set environment variables to non-interactive to avoid prompts during installation
ENV DEBIAN_FRONTEND=noninteractive
ENV ID=ubuntu
ENV VERSION_ID=24.04

# Install dependencies
RUN apt-get update && apt-get install -y wget unzip software-properties-common \
    && add-apt-repository ppa:dotnet/backports \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    dotnet-sdk-6.0 \
    aspnetcore-runtime-7.0 \
    dotnet-host-7.0 \
    dotnet-hostfxr-7.0 \
    dotnet-runtime-7.0 \
    python3 \
    python3-venv \
    python3-pip \
    python3-decouple \
    python3-pandas \
    && rm -rf /var/lib/apt/lists/*
    
# Install Coh-Metrix
RUN wget https://raw.githubusercontent.com/memphis-iis/cohmetrix-issues/refs/heads/main/cohmetrixcorecli-1.0.9_amd64.deb \
    && dpkg -i cohmetrixcorecli-1.0.9_amd64.deb \
    && rm cohmetrixcorecli-1.0.9_amd64.deb

# Download Coh-Metrix data
USER ubuntu
WORKDIR	/home/ubuntu

RUN wget http://cohmetrix.memphis.edu/api/downloadData \
    && mkdir -p /home/ubuntu/.local/share/CohMetrixCore \
    && unzip downloadData -d /home/ubuntu/.local/share/CohMetrixCore/ \
    && rm downloadData

# Setup license
RUN (printf "$COHMETRIX_EMAIL\n$COHMETRIX_API_KEY" && cat) | /usr/local/bin/cohmetrixcorecli/CohMetrixCoreCLI

COPY scripts/feat_psy_cohmetrix.py /home/ubuntu/scripts/feat_psy_cohmetrix.py

CMD ["/usr/local/bin/cohmetrixcorecli/CohMetrixCoreCLI", "/documents", "/report"]
